# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='group',
            name='starosta_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
