# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_secretcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcourse',
            name='groups',
            field=models.ManyToManyField(null=True, to='core.ModelGroup'),
        ),
    ]
