# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modelcourse_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
