# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courses',
            new_name='groups',
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to='core.UserProfile'),
        ),
    ]
