# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170512_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='new_course', max_length=254),
            preserve_default=False,
        ),
    ]
