# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170513_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='beginning_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='ending_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(),
        ),
    ]
