# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170513_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group_id',
            field=models.ForeignKey(default=b'NULL', on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
    ]
