# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170531_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
            preserve_default=False,
        ),
    ]
