# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170531_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group_id',
        ),
    ]
