# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_group_starosta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='starosta_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group_key',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='core.Group'),
        ),
    ]
